# 行列積の実装

##【問題1】行列積を手計算する
---
AとBの行列積を手計算で解いてください。

計算過程もマークダウンテキストを用いて説明してください。

\begin{eqnarray}
A=\left[
\begin{array}{ccc}
-1 & 2 & 3 \\
4 & -5 & 6 \\
7 & 8 & -9 \\
\end{array}
\right], B=\left[
\begin{array}{ccc}
0 & 2 & 1 \\
0 & 2 & -8 \\
2 & 9 & -1 \\
\end{array}
\right]
\end{eqnarray}

行列積の計算は、以下の行列で計算することができる。

\begin{eqnarray}
\left[
\begin{array}{ccc}
a_{1} & a_{2} & a_{3} \\
a_{4} & a_{5} & a_{6} \\
a_{7} & a_{8} & a_{9} \\
\end{array}
\right]×\left[
\begin{array}{ccc}
b_{1} & b_{2} & b_{3} \\
b_{4} & b_{5} & b_{6} \\
b_{7} & b_{8} & b_{9} \\
\end{array}
\right] &=& \left[
\begin{array}{ccc}
a_{1}b_{1}+ a_{2}b_{4}+ a_{3}b_{7}& a_{1}b_{2}+ a_{2}b_{5}+ a_{3}b_{8} & a_{1}b_{3}+ a_{2}b_{6}+ a_{3}b_{9} \\
a_{4}b_{1}+ a_{5}b_{4}+ a_{6}b_{7}& a_{4}b_{2}+ a_{5}b_{5}+ a_{6}b_{8} & a_{4}b_{3}+ a_{5}b_{6}+ a_{6}b_{9} \\
a_{7}b_{1}+ a_{8}b_{4}+ a_{9}b_{7}& a_{7}b_{2}+ a_{8}b_{5}+ a_{9}b_{8} & a_{7}b_{3}+ a_{8}b_{6}+ a_{9}b_{9} \\
\end{array}
\right] \\
&=& \left[
\begin{array}{ccc}
0+0+6& -2+4+27& -1+(-16)+(-3) \\
0+0+12& 8+(-10)+54& 4+40+(-6) \\
0+0+(-18)& 14+16+(-81)& 7+(-64)+9 \\
\end{array}
\right] \\
&=& \left[
\begin{array}{ccc}
6& 29& -20 \\
12& 52& 38 \\
-18& -51& -48 \\
\end{array}
\right]
\end{eqnarray}

## 【問題2】NumPyの関数による計算
---
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。

これらを使い行列積を計算してください。

In [93]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

print("np.matmul()：\n{}".format( np.matmul(a_ndarray, b_ndarray) ))
print("np.dot()：\n{}".format( np.dot(a_ndarray, b_ndarray) ))
print("@演算子：\n{}".format( a_ndarray@b_ndarray ))

np.matmul()：
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
np.dot()：
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
@演算子：
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## 【問題3】ある要素の計算を実装
---
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。

数式で表すと
$$\sum_{k=0}^{2}a_{0,k}b_{k,0}$$
です。  
<br>
この計算を<font color="red">np.matmul()</font>や<font color="red">np.dot()</font>、または<font color="red">@</font>演算子を使わずに行うコードを書いてください。

In [94]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# 計算結果をこのリストに格納する
res_list = []
temp = 0

for i in range(3):
  for j in range(3):
    for k in range(3):
      temp += a_ndarray[i, k] * b_ndarray[k, j]

    res_list.append(temp)
    temp = 0


# リストをndarrayに変更し、形状を再設定する
print(np.array(res_list).reshape(3, 3))


[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## 【問題4】行列積を行う関数の作成
---
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。

In [95]:
def calc_matrix_product(a_ndarray, b_ndarray):
    '''行列積を行う関数
    Parameteres
    -----------
    a_ndarray: 1つ目のndarrayデータ（ndarray型）
    b_ndarray: 2つ目のndarrayデータ（ndarray型）

    Returns
    -------
    res_ndarray : ndarray型
        行列積を実行した結果のndarrayデータ
    '''

    import numpy as np

    row = a_ndarray.shape[0]
    col = b_ndarray.shape[1]

    # 計算結果をこのリストに格納する
    res_list = []

    for i in range(row):
      for j in range(col):
        #a_ndarrayのi行目とb_ndarrayのj列目を掛け合わせ、その全ての要素を足した値をres_listに追加
        res_list.append( (np.sum( a_ndarray[i, :] * b_ndarray[:, j] )) )

    # listをndarrayに変換したし、形状を再設定したndarrayを返す
    res_ndarray = np.array(res_list).reshape(row, col) 
    return res_ndarray


######

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

print( calc_matrix_product(a_ndarray, b_ndarray) )

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


##【問題5】計算が定義されない入力を判定する
---
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。

if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [96]:
def calc_matrix_product_with_check(a_ndarray, b_ndarray):
    '''入力されたndarrayの形に問題があるかをチェックする。問題がある場合はエラーを表示し、問題がない場合は行列積を行う関数
    Parameteres
    -----------
    a_ndarray: 1つ目のndarrayデータ（ndarray型）
    b_ndarray: 2つ目のndarrayデータ（ndarray型）

    Returns
    -------
    res_ndarray : ndarray型
        行列積を実行した結果のndarrayデータ
    '''

    import numpy as np

    # 行列積のマトリクスの形に問題があるかどうかをチェックする
    # 左マトリックスの列数と右マトリックスの行数が等しくない場合は、計算ができないので、エラーメッセージを表示し、関数を終了する
    if a_ndarray.shape[1] != b_ndarray.shape[0]:
      print("インプットされた左マトリックスの列数と右マトリックスの行数が等しくないため、計算ができません。")
      return

    row = a_ndarray.shape[0]
    col = b_ndarray.shape[1]

    # 計算結果をこのリストに格納する
    res_list = []

    for i in range(row):
      for j in range(col):
        #a_ndarrayのi行目とb_ndarrayのj列目を掛け合わせ、その全ての要素を足した値をres_listに追加
        res_list.append( (np.sum( a_ndarray[i, :] * b_ndarray[:, j] )) )

    # listをndarrayに変換したし、形状を再設定したndarrayを返す
    return np.array(res_list).reshape(row, col)


############

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

print( calc_matrix_product_with_check(d_ndarray, e_ndarray) )


インプットされた左マトリックスの列数と右マトリックスの行数が等しくないため、計算ができません。
None


## 【問題6】転置
---
片方の行列を転置することで、行列積が計算できるようになります。

np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [97]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]]).T

print( calc_matrix_product_with_check(d_ndarray, e_ndarray) )

[[ 46  -4]
 [-34  73]]


In [98]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.transpose( np.array([[-9, 8, 7], [6, -5, 4]]))

print( calc_matrix_product_with_check(d_ndarray, e_ndarray) )

[[ 46  -4]
 [-34  73]]
