# Week4-3
## 【問題1】これまで利用してきたクラスの列挙
---
クラスを使う際はインスタンス化を行うことと、クラスの命名法がわかりました。この情報を元に、これまでの課題で利用してきたコードの中でどのようなクラスがあったかを答えてください。

Pandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。

### Pandasのクラス
> DataFrame, Series
### matplotlibのクラス
> matplotlib.pyplot, figure.Figure, Axes3D
### scikit-learnのクラス
> LinearRegression, RandomForestRegressor, SVR, DecisionTreeRegressor

## 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙
---
これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。

最低でもそれぞれ5つ以上答えてください。

>メソッド
```python
df.info() 
plt.title(title_str, fontsize=15)
time.time()
np.concatenate([data1_labeled, data2_labeled])
res_list.reshape(3, 3)
np.sum()
```

>インスタンス変数
```python
model.coef_
model.intercept_
math.pi
math.e
fig.dpi
```

## 【問題3】標準化クラスをスクラッチで作成
---
理解をより深めるため、<font color='red'>StandardScaler</font>をスクラッチで作成しましょう。scikit-learnは使わず、NumPyなどを活用して標準化の計算を記述します。具体的にはfitメソッドとtransformメソッドを作ります。

In [106]:
class ScratchStandardScaler():
    """
    標準化のためのクラス
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = np.mean(X, axis=0) # 列ごとに平均する
        self.var_ = np.var(X, axis=0)   # 列ごとに平均する
        
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量
        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        
        # 標準化　＝　(各データ - データセットの平均値) ÷ データセットの標準偏差(=√分散)
        # 標準化をするとデータセットの平均がゼロ、標準偏差値が１になっていること
        X_scaled = (X - self.mean_)/np.sqrt(self.var_)
        
        return X_scaled

In [107]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


> <<コンストラクタのサンプルコード>>　

In [108]:
class ExampleClass():
    """
    説明用の簡単なクラス
    Parameters
    ----------
    value : float or int
        初期値
    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))



初期値5が設定されました
value : 5
value : 8


## 【問題4】 四則演算を行うクラスの作成
---
上記ExampleClassは足し算のメソッドを持っていますが、これに引き算、掛け算、割り算のメソッドを加えてください。

コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合にはエラーを出すようにしてください。

クラス名や説明文も適切に書き換えてください。

In [109]:
class FourArithmeticOperations():
    """
    四則演算を行うクラス
    Parameters
    ----------
    value : float or int
        初期値
    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        try:
            self.value = value
        except TypeError:
            print("Input value is not vaild number.")
        
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        try:
            self.value += value2
        except TypeError:
            print("Input value is not vaild number.")
    def subtract(self, value3):
        """
        受け取った引数をself.valueから減算する
        """
        try:
            self.value -= value3
        except TypeError:
            print("Input value is not vaild number.")
            
    def multiply(self, value4):
        """
        受け取った引数をself.valueに掛ける
        """
        try:
            self.value *= value4
        except TypeError:
            print("Input value is not vaild number.")
    
    def divide(self, value5):
        """
        self.valueを受け取った引数で割る
        """
        try:
            self.value /= value5
        except TypeError:
            print("Input value is not vaild number.")
        
example = FourArithmeticOperations(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
example.subtract(2)
print("value : {}".format(example.value))
example.multiply(4)
print("value : {}".format(example.value))
example.divide(6)
print("value : {}".format(example.value))

value : 5
value : 8
value : 6
value : 24
value : 4.0
